### ISSUE TITLE
Merging gudFPS and FabricZero?

### ISSUE THREAD

**Issue by Fox2Code** [gudenau/minecraft-gudfps#2]
I have a mod that is extremely similar mod named [FabricZero](https://github.com/Fox2Code/FabricZero)

Both mod are a bit "duplicate" so the idea is to merge both mods in the same project. *(Even if it's partially)*

So the idea is to put the code of FabricZero in this project or vice versa.  
*(If you want to add your code to my project I add you write perms to the repo)*  
A third option is to do the merge in a new repo to do the bases from scratch.

With both mods working similarly it shouldn't be hard to merge both projects.  
(For example, gudFPS and FabricZero use the same `IMixinConfigPlugin`/`FabricMixinTransformerProxy` method to inject)

I made a [Java9Fix](https://github.com/Fox2Code/FabricZero/blob/master/src/main/java/com/fox2code/fabriczero/reflectutils/Java9Fix.java) to try to fix reflection problems *(Got a bit messy when I tried to make it work with Java14)* 
And finally used a [trick involving invalid bytecode](https://github.com/Fox2Code/FabricZero/blob/master/Special/src/main/java/com/fox2code/fabriczero/reflectutils/SetAccessibleHax.java) and `-Xverify:none` by [restarting the JVM](https://github.com/Fox2Code/FabricZero/blob/master/src/main/java/com/fox2code/fabriczero/reflectutils/AutoFixer.java)  

But I think my system should be replaced by `C++` code since JNI doesn't seem to be restricted for reflections.  
*(You can't do [`field.setAccessible(true);`](https://github.com/gudenau/minecraft-gudfps/blob/0c6b7d4730a2c6106eb1f070e362b601945f90d5/src/main/java/net/gudenau/minecraft/fps/util/ReflectionHelper.java#L29) in the latests java environements)*

If you want to talk more about this you can contact me on Discord: Fox2Code#2319

**Comment by gudenau** [comment]
I do appreciate the offer but this project is mostly for my entertainment and education.

This mod is not intended to work with other mods but it does not go out of it's way to break them either, while yours appears to do it's best to make everything work together.

I don't think I will go with this, but you can take inspiration from my code base if you want.

**Comment by Fox2Code** [comment]
It's just I saw that your mod use bytecode optimization methods that I didn't use before.

I also made FabricZero for fun I like trying to make everything compatible.

Do you allow me to use the code of this project in other projects if you are credited?  
And if yes under which condition? (OpenSource Licence / Aditional restrictions)

**Comment by gudenau** [comment]
I really need to pick a licence. I'll go figure that out.

**Comment by Fox2Code** [comment]
Ok thank

Also there this website if you need help to choose a license: https://choosealicense.com/

**Comment by Kichura** [comment]
> 
> 
> I really need to pick a licence. I'll go figure that out.

Dropping this reply to make it simple: You can choose the MIT license if you wanna the easy way, But i recommend LGPL v3 for most mods.
